name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        exampleDir:
          - lit
          - preact
          - react
          - svelte
          - vue
          - solid
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: |
            npm install
            rm -r ./node_modules/chromedriver
            npm i chromedriver --detect_chromedriver_version
          working-directory: ${{ matrix.exampleDir }}
        - name: Test
          run: npm run wdio
          working-directory: ${{ matrix.exampleDir }}